/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.clevervitor.hotelpet.view;

import com.clevervitor.hotelpet.controller.AgendamentoController;
import com.clevervitor.hotelpet.controller.FuncionarioController;
import com.clevervitor.hotelpet.controller.PetController;
import com.clevervitor.hotelpet.controller.ProprietarioController;
import com.clevervitor.hotelpet.model.entities.Funcionario;
import com.clevervitor.hotelpet.view.dialogs.DlgCadProprietario;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author clevs
 */
public class FrMainMenuFuncioario extends javax.swing.JDialog {

    /**
     * Creates new form mainMenu
     */
    private Funcionario funcionarioLogado;
    private FuncionarioController funcionarioCont;
    private AgendamentoController agendamentoCont;
    private PetController petCont;
    private ProprietarioController proprietarioCont;

    public FrMainMenuFuncioario(Funcionario funcionario) {
        initComponents();

        this.funcionarioLogado = funcionario;
        this.funcionarioCont = new FuncionarioController();
        this.agendamentoCont = new AgendamentoController();
        this.petCont = new PetController();
        this.proprietarioCont = new ProprietarioController();

        Image iconeTitulo = null;
        try {
            iconeTitulo = ImageIO.read(getClass().getResource("/Imagens/pawprint.png"));
        } catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        setIconImage(iconeTitulo);
        habilitarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        pnlControleGeral = new javax.swing.JPanel();
        pnlComAbas = new javax.swing.JTabbedPane();
        abaAgendamentos = new javax.swing.JScrollPane();
        tblAgendamentos = new javax.swing.JTable();
        abaProprietarios = new javax.swing.JPanel();
        scrProprietarios = new javax.swing.JScrollPane();
        tblProprietarios = new javax.swing.JTable();
        abaPets = new javax.swing.JPanel();
        scrPets = new javax.swing.JScrollPane();
        tblPets = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        pnlInfo.setBackground(new java.awt.Color(51, 51, 51));
        pnlInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Painel de Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft PhagsPa", 1, 24), new java.awt.Color(242, 242, 242))); // NOI18N
        pnlInfo.setForeground(new java.awt.Color(51, 153, 255));

        jButton1.setText("Foto");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);

        lblNome.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(242, 242, 242));
        lblNome.setText("Nome");

        lblContato.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        lblContato.setForeground(new java.awt.Color(242, 242, 242));
        lblContato.setText("Contato");

        lblEmail.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(242, 242, 242));
        lblEmail.setText("Email");

        lblDocumento.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        lblDocumento.setForeground(new java.awt.Color(242, 242, 242));
        lblDocumento.setText("Doc.");

        lblBemVindo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(242, 242, 242));
        lblBemVindo.setText("Seja bem-vindo de volta,");

        lblCargo.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(242, 242, 242));
        lblCargo.setText("Cargo");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocumento)
                    .addComponent(lblContato)
                    .addComponent(lblEmail)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(lblBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome))
                    .addComponent(lblCargo))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBemVindo)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCargo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlControleGeral.setBackground(new java.awt.Color(51, 51, 51));
        pnlControleGeral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nuport", 1, 18), new java.awt.Color(242, 242, 242))); // NOI18N

        pnlComAbas.setBackground(new java.awt.Color(204, 204, 204));
        pnlComAbas.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        abaAgendamentos.setBackground(new java.awt.Color(51, 51, 51));

        tblAgendamentos.setBackground(new java.awt.Color(51, 51, 51));
        tblAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        abaAgendamentos.setViewportView(tblAgendamentos);

        pnlComAbas.addTab("Agendamentos", abaAgendamentos);

        abaProprietarios.setBackground(new java.awt.Color(51, 51, 51));

        scrProprietarios.setBackground(new java.awt.Color(51, 51, 51));

        tblProprietarios.setBackground(new java.awt.Color(51, 51, 51));
        tblProprietarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrProprietarios.setViewportView(tblProprietarios);

        javax.swing.GroupLayout abaProprietariosLayout = new javax.swing.GroupLayout(abaProprietarios);
        abaProprietarios.setLayout(abaProprietariosLayout);
        abaProprietariosLayout.setHorizontalGroup(
            abaProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrProprietarios, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        abaProprietariosLayout.setVerticalGroup(
            abaProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaProprietariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrProprietarios, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlComAbas.addTab("Proprietarios", abaProprietarios);

        abaPets.setBackground(new java.awt.Color(51, 51, 51));

        scrPets.setBackground(new java.awt.Color(51, 51, 51));

        tblPets.setBackground(new java.awt.Color(51, 51, 51));
        tblPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrPets.setViewportView(tblPets);

        javax.swing.GroupLayout abaPetsLayout = new javax.swing.GroupLayout(abaPets);
        abaPets.setLayout(abaPetsLayout);
        abaPetsLayout.setHorizontalGroup(
            abaPetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPets, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        abaPetsLayout.setVerticalGroup(
            abaPetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPetsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPets, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );

        pnlComAbas.addTab("Pets", abaPets);

        javax.swing.GroupLayout pnlControleGeralLayout = new javax.swing.GroupLayout(pnlControleGeral);
        pnlControleGeral.setLayout(pnlControleGeralLayout);
        pnlControleGeralLayout.setHorizontalGroup(
            pnlControleGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControleGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlComAbas)
                .addContainerGap())
        );
        pnlControleGeralLayout.setVerticalGroup(
            pnlControleGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleGeralLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlComAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu3.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);
        jMenu3.add(jSeparator1);

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("jMenu1");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlControleGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 168, Short.MAX_VALUE)
                    .addComponent(pnlControleGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void habilitarCampos() {

        lblBemVindo.setForeground(new Color(187, 187, 187));

        lblNome.setText(funcionarioLogado.getNome());
        lblNome.setForeground(new Color(187, 187, 187));

        lblEmail.setText(funcionarioLogado.getEmail());
        lblEmail.setForeground(new Color(187, 187, 187));

        lblDocumento.setText(funcionarioLogado.getCpf());
        lblDocumento.setForeground(new Color(187, 187, 187));

        lblContato.setText(funcionarioLogado.getTel());
        lblContato.setForeground(new Color(187, 187, 187));

        lblCargo.setText(funcionarioLogado.getCargo());
        lblCargo.setForeground(new Color(187, 187, 187));

        agendamentoCont.atualizarTabelaDeAgendamentos(tblAgendamentos, agendamentoCont.buscarTodosOsAgendamentos());
        proprietarioCont.atualizarTabelaDeProprietarios(tblProprietarios, proprietarioCont.buscarTodosOsProprietarios());
        petCont.atualizarTabelaDePets(tblPets, petCont.buscarTodosOsPets());

    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrLogin TLogin = new FrLogin();
        TLogin.setTitle("Login");
        TLogin.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DlgCadProprietario cadastroProp = new DlgCadProprietario(new Frame(), true);
        cadastroProp.setTitle("Cadastro");
        cadastroProp.setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane abaAgendamentos;
    private javax.swing.JPanel abaPets;
    private javax.swing.JPanel abaProprietarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTabbedPane pnlComAbas;
    private javax.swing.JPanel pnlControleGeral;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JScrollPane scrPets;
    private javax.swing.JScrollPane scrProprietarios;
    private javax.swing.JTable tblAgendamentos;
    private javax.swing.JTable tblPets;
    private javax.swing.JTable tblProprietarios;
    // End of variables declaration//GEN-END:variables
}
